name: Sugerir uma melhoria
description: Proponha uma funcionalidade, ajuste de design ou melhoria de documentação.
title: "[Melhoria]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual necessidade esta proposta atende?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solução proposta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
